### ISSUE TITLE
Why do `supported_...` methods return Option ?

### ISSUE THREAD

**Issue by jonasBoss** [emberian/evdev#117]
I frequently find my self writing something like
```rust
device.supported_keys().unwrap_or(&AttributeSet::new())
```
which is kind of wired, because `supported_...` returns a collection so why does it return None if the collection is empty?

Even if I get the `Some(&AttributeSetRef)` variant no one guarantees me that the `AttributeSet` contains elements. So my code needs to handle the case where the `AttributeSet` is empty anyway. That leads me to the pattern from above.

From a user perspective, I can not think of any reason why I would ever do something with the `None` Variant. If I want to know if a device supports keys I would just call `supported_events()`.

**Comment by jeff-hiner** [comment]
It's trying to be a transparent interface to the underlying system calls. I don't know of any devices for which this is true, but it's theoretically possible for `eviocgbit_type` to report that a device supports keys, but for `eviocgbit_key` to return an empty set.

If you want to collapse the two cases without checking `supported_events` and unwrapping `supported_key`, turning the Option into an iterator and then flattening will do what you want without having to create a new `AttributeSet`: `.into_iter().flat_map(AttributeSetRef::iter)`

**Comment by coolreader18** [comment]
Another thing we could do to make it slightly less annoying is impl Default for `&AttributeSetRef` (delegating to creating an empty BitSlice), so that it's just `device.supported_keys().unwrap_or_default()`
