### ISSUE TITLE
v0.12.1 has the wrong `/dev/` path for `enumerate_dev_nodes_blocking`

### ISSUE THREAD

**Issue by jtroo** [emberian/evdev#129]
Thanks for the work on this crate!

A user of my project discovered a bug in v0.12.1 where the dev node paths have changed since v0.12.0. It remains an iterator with a single entry as expected, but the single entry has an unexpected path.

https://github.com/jtroo/kanata/issues/455

> The symlink which Kanata creates for the virtual output device points at /sys/devices/virtual/input/input8/event1 which is a folder with a bunch of metadata rather than the expected /dev/input/event1.
> The Created device /path/to/device message shows the same incorrect path.

**Comment by mattfbacon** [comment]
I traced this back to 50a33695. The commit message is not really correct because in addition to removing the loop and returning `Ok(None)` at the end it also changes the behavior by removing the path manipulation. I would open a PR but I think this repository is abandoned.

**Comment by jeff-hiner** [comment]
As far as I know the crate is still active. I'm still a reviewer and have merge perms, but I don't have permissions to publish. If you submit a PR I'll take a look.

**Comment by emberian** [comment]
not quite abandoned, i'll merge and release any important PRs

**Comment by mattfbacon** [comment]
Good to know

**Comment by wolfwood** [comment]
a bisect using kanata points to d0231e3c626316b18de59eec5d1ff8a344d94c9e as the commit responsible. reverting this commit on top of 0.12.1 allows kanata to retain the previous behavior.

I've made PR #147 with the revert. Ideally though would be a 0.12.2 release that cherrypicks the revert on top of 0.12.1. I have a branch with that here: f17826fed3b3c69cbc0b262f02f0581351d47008

**Comment by coolreader18** [comment]
Released 0.12.2!

**Comment by wolfwood** [comment]
Thanks @coolreader18 ! This works in my testing.
