### ISSUE TITLE
Allow finer-grained permissions when opening a device

### ISSUE THREAD

**Issue by conqp** [emberian/evdev#131]
While programming [`beep-evdev`](https://github.com/conqp/beep-evdev/), I realized that [`Device::open()`](https://github.com/emberian/evdev/blob/4c2b3196ab9ccf00400e19e698265412091c0a1e/src/sync_stream.rs#L45) and inside of it [`RawDevice`](https://github.com/emberian/evdev/blob/4c2b3196ab9ccf00400e19e698265412091c0a1e/src/raw_stream.rs#L152) always attempt to open with `read` and `write` permissions.
However, for my use case it would suffice to only have the `append` permission (and neither read nor write).

Is it possible to add a function to `Device` and `RawDevice` respectively, to allow to pass in pre-configured `OpenOptions`?
I'm thinking of something like `open_with_options(path: impl AsRef<Path>, open_options: &OpenOptions)`.

Another possibility would be to implement `From<std::fs::File>` for `Device` and `RawDevice` respectively.
Then I could do:

```rust
let device: Device = OpenOptions::new()
    .append(true)
    .open(FILENAME)
    .into();
```

I'd be happy to draft a PR if this proposal is met with approval.

**Comment by conqp** [comment]
With the pull request above, the following beep program works with lower privileges:
```rust
use evdev::{Device, EventType, InputEvent, SoundCode};
use std::{fs::OpenOptions, thread, time};

const FILE: &str = "/dev/input/by-path/platform-pcspkr-event-spkr";

pub fn beep(hertz: u16) -> std::io::Result<()> {
    Device::try_from(OpenOptions::new().append(true).open(FILE)?)?.send_events(&[InputEvent::new(
        EventType::SOUND.0,
        SoundCode::SND_TONE.0,
        i32::from(hertz),
    )])
}

fn main() {
    beep(440).expect("could not beep");
    thread::sleep(time::Duration::from_millis(500));
    beep(880).expect("could not beep");
    thread::sleep(time::Duration::from_millis(500));
    beep(0).expect("could not beep");
}
```

Udev rules:
```
ACTION=="add", SUBSYSTEM=="input", ATTRS{name}=="PC Speaker", ENV{DEVNAME}!="", GROUP="beep", MODE="0620"
```

**Comment by hendursaga** [comment]
@conqp I know this is closed, but I was wondering what's the practical security difference between write and append, in this context?

**Comment by conqp** [comment]
Bak in the day when I wrote beep-evdev, it did not work with write and the aforementioned udev rule. I haven't been working with beep-evdev and udev lately, so I don't know what precisely was the issue. Are you able to reproduce it?
Also with the append permission rather than write, a user will never be able to accidentally create the file if it does not exist in the first place, though they'd need write permission on the parent directory anyway. But better be safe than sorry.

**Comment by hendursaga** [comment]
@conqp no, I haven't had an issue, I just saw this and wondered what the practical security differences between append and write were.

**Comment by SludgePhD** [comment]
Your udev rule is wrong, `MODE="0620"` will only give write, not read, permission to group members. `MODE="0660"` will give both read and write permission to group members.

`append` is not a Unix permission, it is equivalent to the `write` permission and a flag (`O_APPEND`) that tells `open(2)` to seek to the end of the file (which device files tend to ignore). Your workaround is equivalent to opening the file with `write` permission, but without `read` permission.
