### ISSUE TITLE
eviocgbit uses bit count instead of byte count

### ISSUE THREAD

**Issue by hcs64** [emberian/evdev#14]
Bit count is being used in a few places where a byte count is expected, like the [eviocgbit](https://github.com/cmr/evdev/blob/04761b788fcd6722b6283fb98d1578b81559fd1a/src/lib.rs#L750-L785) length arguments. Having these use the size in bytes (from `std::mem::size_of_val(x.as_mut_slice())`) instead quieted warnings from valgrind. This is consistent with how libevdev uses `sizeof`.

For the most part I don't think this matters as the kernel uses the size of the structure as the max, but sometimes that size is one `long` longer than actually needed (or allocated by `FixedBitSet`).

**Comment by emberian** [comment]
Whoops! Excellent observation and good catch, thank you.

**Comment by jeff-hiner** [comment]
I'd like to fix and fold this into a 0.11 release. I'll start a new set of PRs when https://github.com/emberian/evdev/pull/24 is merged.
