### ISSUE TITLE
Implement Debug for Device

### ISSUE THREAD

**Issue by maxbla** [emberian/evdev#17]
[`Debug`](https://doc.rust-lang.org/std/fmt/trait.Debug.html) is generally helpful for, well, debugging. Probably every struct should implement debug, but I particularly found myself wanting an implementation for Device. The rust docs even say: "Generally speaking, you should just derive a Debug implementation."

**Comment by emberian** [comment]
I agree.

**Comment by jeff-hiner** [comment]
It looks like `Device` currently has a `Debug` impl in master, and it should be switched over to auto-derived soon. Closing this.
