### ISSUE TITLE
Why are multitouch axes intentionally not requested?

### ISSUE THREAD

**Issue by LinusCDE** [emberian/evdev#20]
When trying to use the input_absinfo for ABS_MT_POSITION_X/Y, I noticed them being 0. After stracing the program, I noticed that most absolute axes on another device with abs axes were grabbed fine with an eviocgabs ioctl. But not my multitouch ones which evtest could clearly find.

My [first finding](https://github.com/emberian/evdev/blob/62bb393491b9d2eeffa7a99a99cf0e2591b0c11c/src/lib.rs#L798) that 0x28 was not all the ABS values (would be 0x3f) didn't work. The I noticed the comment below the finding which explicitly ignored the ABS_MT values.

It seems that I can grab the axis without problem. What was the intention of "we'll handle that later.". Is there any extra checking that needs to be done for those that I missed? For now my fix seems to work just fine (https://github.com/LinusCDE/evdev/commit/43fb0b33994dba667ab3f1c107b7393ac3166ffe). I needed the fix for [this code](https://github.com/LinusCDE/libremarkable/blob/d2d365ed5d2e8b7c867a8e91c2f5be5109e440b1/src/input/scan.rs#L114) to work.

**Comment by emberian** [comment]
fixed by #21
