### ISSUE TITLE
We need an optional async (tokio) stream of events

### ISSUE THREAD

**Issue by jeff-hiner** [emberian/evdev#35]
Obviously this should be feature-gated since we don't want to import all of tokio for those who don't want it. But this crate is just begging for an async stream of InputEvent that can be driven by an async reactor instead of trying to drive it manually with epoll.

**Comment by Ralith** [comment]
If a fd and polling function are exposed, downstream users should be able to very easily turn that into a stream on their own without baking in any particular version of any particular runtime.

**Comment by coolreader18** [comment]
The file descriptor is exposed, but it would be much more ergonomic for users if we were to support one or a few of the most popular runtimes.
