### ISSUE TITLE
Support for absolute axes in VirtualDeviceBuilder

### ISSUE THREAD

**Issue by Yamakaky** [emberian/evdev#48]
Currently, only Key and RelativeAxis are supported in VirtualDeviceBuilder. This prevents it from being used as a a virtual gamepad.

Example in C: https://github.com/GrantEdwards/uinput-joystick-demo/blob/master/uinput-demo.c#L171

**Comment by StephanvanSchaik** [comment]
This has been addressed by #71.

**Comment by Yamakaky** [comment]
Nice!
