### ISSUE TITLE
Easier AttributeSet creation

### ISSUE THREAD

**Issue by Yamakaky** [emberian/evdev#49]
Currently, to create an AttributeSet, we need to do a list on `.insert` or a loop. It would be nice to be able to do it via a constructor, for example `AttributeSet::with_values(&[Key::BTN_A, Key::BTN_B])`.

**Comment by StephanvanSchaik** [comment]
It is currently possible to create an `AttributeSet` from an array/iterator like in the following example:

```
let keys = AttributeSet::from_iter([Key::BTN_A, Key::BTN_B]);
```

**Comment by Yamakaky** [comment]
Thanks, maybe it was added in the mean time !
