### ISSUE TITLE
Missing LICENSE files

### ISSUE THREAD

**Issue by mbway** [emberian/evdev#68]
There is no indication what the license is for this library which is not ideal. [Technically this means that it is proprietary](https://choosealicense.com/no-permission/).

My suggestion for which license to use is the MIT license since it is a popular/uncontroversial license and [libevdev uses it as well](https://gitlab.freedesktop.org/libevdev/libevdev/-/blob/master/COPYING).

**Comment by jeff-hiner** [comment]
The license specified in Cargo.toml is "Apache-2.0 OR MIT", meaning you can choose either one according to your needs.
https://github.com/emberian/evdev/blob/372d000c21b1ff7f47a16c10fb9859d04e885bcd/Cargo.toml#L6

**Comment by mbway** [comment]
ah, ok. I was looking for a LICENSE or COPYING file but that works too.

**Comment by jeff-hiner** [comment]
Yeah I'm open to a PR to add a LICENSE file, as long as we can somehow do both. I'm not sure how Github does the auto-detect for licenses, and I don't want it to read the first line and go "oh yeah it's MIT" or "oh yeah it's Apache 2.0".

**Comment by coolreader18** [comment]
I think usually it would be a `LICENSE-MIT` and `LICENSE-APACHE`

**Comment by coolreader18** [comment]
e.g. as in https://github.com/rust-lang/rust/
