### ISSUE TITLE
virtual keyboard example

### ISSUE THREAD

**Issue by dbuchacher** [emberian/evdev#69]
Hi, I'm trying to figure out what this **No such file or directory** error message is trying to find?

This is my console output below. (i get same message as root as well)

```shell
user@gentoo evdev % cargo run --example virtual_keyboard
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/virtual_keyboard`
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by coolreader18** [comment]
Do you have `/dev/uinput`?

**Comment by dbuchacher** [comment]
Thank you.  That helped me find a solution.  Needed to add uinput support into kernel and recompile.

## Solution
```shell
nano /usr/src/linux/.config
```
before
```
# Input Device Drivers

# CONFIG_INPUT_UINPUT is not set
```

after
```
# Input Device Drivers

CONFIG_INPUT_UINPUT=y
```

```shell
make
make modules_install
make install
```

warning use your distros proper process for grub update (this was mine)
```shell
grub-mkconfig -o /boot/grub/grub.cfg
```

then reboot pc

**Comment by dbuchacher** [comment]
Solved
