### ISSUE TITLE
Unexpected abs bits

### ISSUE THREAD

**Issue by oberien** [emberian/evdev#7]
When running `evdev::enumerate` I get the following output:

```
abs bits: 11110000000100000000000000000000000000000000
thread 'main' panicked at 'evdev: unexpected abs bits! report a bug'
```

I guess I was asked to open this issue ;)

As I don't know which exact infos you need, I'll just post my `xinput` output for now. Feel free to ask for additional information.

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech USB Receiver                   	id=9	[slave  pointer  (2)]
⎜   ↳ Logitech USB Receiver                   	id=10	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Burr-Brown from TI               USB Audio CODEC 	id=13	[slave  keyboard (3)]
    ↳ Logitech Gaming Keyboard G910           	id=11	[slave  keyboard (3)]
    ↳ Logitech Gaming Keyboard G910           	id=12	[slave  keyboard (3)]
```

**Comment by cmr** [comment]
Hi, can you try again with evdev 0.10.0?

**Comment by cmr** [comment]
Make that 0.10.1 :)

**Comment by oberien** [comment]
I still get the same panic. Cloning this repo and printing `bits64` just before the `expect` still gives me `11110000000100000000000000000000000000000000`.

**Comment by cmr** [comment]
What is your kernel version?

**Comment by oberien** [comment]
Linux 4.10.13-1-vfio #1 SMP PREEMPT Tue May 2 07:27:05 CEST 2017 x86_64 GNU/Linux

I use an AUR package on arch to compile the kernel with a vfio "fix": https://aur.archlinux.org/pkgbase/linux-vfio/

**Comment by cmr** [comment]
Well, as far as I can tell, one of your devices is indeed setting an unknown absolute axis support bit... I'm not sure what to do about that. (eg, bit 0x2b is set)

**Comment by cmr** [comment]
(Unknown in that it isn't even part of the kernel header)

**Comment by Ralith** [comment]
It would be nice to be able to support axes that aren't in the header, since even aside from weird drivers, the header will receive extensions in the future. libevdev is written to handle this case, for example. An axis is just identified by an index, after all; having a `#define` for that index isn't that important.

**Comment by Ralith** [comment]
Using constants instead of bitflags for everything would also considerably simplify matching on `input_event`, which afaict is the overwhelmingly common use pattern.

**Comment by oberien** [comment]
I found out that the cause of this issue is my Logitech G602 mouse.

**Comment by Ralith** [comment]
IMO this is a fairly serious forwards-compatibility bug.

**Comment by Xandaros** [comment]
I have the same issue, but with "rel" bits. To make matters worse, the device I want to open (my mouse) is the one responsible. So not only can I not enumerate the devices, I also cannot open the device I am interested in.

**Comment by flukejones** [comment]
Now coming across the 'evdev: unexpected rel bits! report a bug' myself. Using the git master branch seems fine - maybe it's time for another release on crates?

**Comment by jeff-hiner** [comment]
Looks like this is a bit of a structural issue. I'll see if I can't draft up a PR shortly to address this.

**Comment by jeff-hiner** [comment]
I was beaten to it. The capability enumeration has been reworked into `bitvec` and this library will no longer panic if it doesn't recognize an abs axis or rel axis by name.
