### ISSUE TITLE
mismatched types in lib.rs

### ISSUE THREAD

**Issue by ottk3** [emberian/evdev#87]
I get a compile-error in the lib.rs. I'm not sure if this is just a 32-bit system related issue.

> **error[E0308]:** mismatched types
>let dur = Duration::new(tv.tv_sec.unsigned_abs(), tv.tv_usec as u32 * 1000);
>expected `u64`, found `u32`

https://github.com/emberian/evdev/blob/14881c1ac6bacbe1693e813b4ae413d2368c524c/src/lib.rs#L391-L398

**Comment by jeff-hiner** [comment]
Duplicate of https://github.com/emberian/evdev/issues/81
